from typing import List, Optional
from models.schemas import AgentManifest, RiskLevel

SPECIALIZED_AGENTS: List[AgentManifest] = [
    AgentManifest(
        id="agent-research",
        name="RESEARCH-01",
        role="Codebase & Technical RFC Researcher",
        category="Research",
        autonomy_tier="Autonomous",
        allowed_tools=["grep", "ast_search", "web_search", "doc_reader"],
        risk_level=RiskLevel.LOW,
        project_scope=["*"],
        execution_policy="Read-only inquiry and documentation indexing. Strictly prohibited from file writes.",
        model="Gemini 2.5 Pro / Flash",
        avatar="🔬",
        color="#00f0ff",
        capabilities=["Codebase topology search", "Dependency graph analysis", "RFC summarization"],
        status="idle",
        current_task="Standby",
        task_count=54,
        token_velocity=0,
        total_tokens=145200
    ),
    AgentManifest(
        id="agent-dev",
        name="DEVELOPER-02",
        role="Autonomous Feature & Refactoring Synthesizer",
        category="Engineering",
        autonomy_tier="Guardrailed",
        allowed_tools=["file_editor", "code_patcher", "linter", "git_branch"],
        risk_level=RiskLevel.MEDIUM,
        project_scope=["portfolio", "control-center", "mera_project"],
        execution_policy="Permitted to create feature branches and stage code. Direct pushes to main prohibited.",
        model="Claude 3.7 Sonnet / Antigravity Agent",
        avatar="💻",
        color="#00ff9d",
        capabilities=["Component synthesis", "TypeScript refactoring", "Bug squashing"],
        status="idle",
        current_task="Standby",
        task_count=182,
        token_velocity=0,
        total_tokens=492100
    ),
    AgentManifest(
        id="agent-security",
        name="SENTINEL-SEC",
        role="Secret Leak Auditor & AST Vulnerability Scanner",
        category="Security",
        autonomy_tier="Autonomous",
        allowed_tools=["regex_audit", "cve_lookup", "secret_detector", "iam_inspector"],
        risk_level=RiskLevel.HIGH,
        project_scope=["*"],
        execution_policy="Autonomous scanning. Quarantine and permission alterations require human clearance.",
        model="Gemini 2.0 Flash Security",
        avatar="🛡️",
        color="#ff3366",
        capabilities=["Key leak detection", "Dependency CVE audit", "Zero-trust verification"],
        status="monitoring",
        current_task="Continuous AST secret detection scan",
        task_count=320,
        token_velocity=40,
        total_tokens=784900
    ),
    AgentManifest(
        id="agent-qa",
        name="QA-VERIFIER",
        role="Automated Unit, E2E & Smoke Test Runner",
        category="Quality Assurance",
        autonomy_tier="Autonomous",
        allowed_tools=["pytest_runner", "npm_test_runner", "curl_probe", "coverage_inspector"],
        risk_level=RiskLevel.LOW,
        project_scope=["*"],
        execution_policy="Read-only test execution in isolated sandbox. Reports pass/fail deltas.",
        model="Gemini 2.5 Flash",
        avatar="🧪",
        color="#a855f7",
        capabilities=["Regression testing", "Assertion verification", "Test coverage reports"],
        status="idle",
        current_task="Standby",
        task_count=98,
        token_velocity=0,
        total_tokens=210300
    ),
    AgentManifest(
        id="agent-docs",
        name="DOC-CHRONICLER",
        role="Architecture Decision Record & API Documentation Writer",
        category="Documentation",
        autonomy_tier="Autonomous",
        allowed_tools=["doc_writer", "openapi_generator", "markdown_formatter"],
        risk_level=RiskLevel.LOW,
        project_scope=["*"],
        execution_policy="Writes documentation to /docs or markdown stores. Does not alter runtime code.",
        model="DeepSeek R1 / Gemini",
        avatar="📚",
        color="#38bdf8",
        capabilities=["ADR synthesis", "OpenAPI spec docs", "Changelog generation"],
        status="idle",
        current_task="Standby",
        task_count=67,
        token_velocity=0,
        total_tokens=154200
    ),
    AgentManifest(
        id="agent-devops",
        name="DEVOPS-RUNNER",
        role="Containerization & CI/CD Pipeline Orchestrator",
        category="Operations",
        autonomy_tier="Guardrailed",
        allowed_tools=["dockerfile_gen", "github_actions_writer", "build_verifier"],
        risk_level=RiskLevel.HIGH,
        project_scope=["personal-engineering-os-2026", "control-center"],
        execution_policy="Can stage container configs and CI pipelines. Triggering live production pushes requires approval.",
        model="Llama 3.3 70B",
        avatar="⚙️",
        color="#eab308",
        capabilities=["Multi-stage Docker builds", "Workload Identity CI", "Artifact management"],
        status="idle",
        current_task="Standby",
        task_count=115,
        token_velocity=0,
        total_tokens=312400
    ),
    AgentManifest(
        id="agent-infra",
        name="INFRA-ENGINEER",
        role="GCP Cloud Infrastructure & Workload Identity Daemon",
        category="Infrastructure",
        autonomy_tier="Step-by-Step",
        allowed_tools=["gcloud_cli", "iam_manager", "service_account_tool"],
        risk_level=RiskLevel.CRITICAL,
        project_scope=["personal-engineering-os-2026"],
        execution_policy="All cloud modifications, IAM bindings, or API toggles require strict policy compliance and human signoff.",
        model="Gemini 2.5 Pro",
        avatar="☁️",
        color="#6366f1",
        capabilities=["Workload Identity configuration", "Service Account management", "Resource isolation"],
        status="idle",
        current_task="Standby",
        task_count=84,
        token_velocity=0,
        total_tokens=195600
    ),
    AgentManifest(
        id="agent-data",
        name="DATA-CATALYST",
        role="Schema Migration & Data Store Observer",
        category="Data",
        autonomy_tier="Guardrailed",
        allowed_tools=["sqlite_inspector", "json_vault_query", "schema_validator"],
        risk_level=RiskLevel.HIGH,
        project_scope=["control-center"],
        execution_policy="Read operations autonomous. Destructive drops or migrations require human clearance.",
        model="Claude 3.7",
        avatar="💾",
        color="#ec4899",
        capabilities=["JSON memory migration", "Telemetry aggregation", "Consistency validation"],
        status="idle",
        current_task="Standby",
        task_count=41,
        token_velocity=0,
        total_tokens=89200
    ),
    AgentManifest(
        id="agent-ux",
        name="UX-TACTICIAN",
        role="Mobile-First Cyber-HUD & Design System Architect",
        category="Frontend",
        autonomy_tier="Autonomous",
        allowed_tools=["css_stylist", "react_component_gen", "tailwind_optimizer"],
        risk_level=RiskLevel.LOW,
        project_scope=["control-center", "portfolio"],
        execution_policy="Design tokens and layout optimization. Pure frontend sandbox.",
        model="Claude 3.7 Sonnet",
        avatar="🎨",
        color="#14b8a6",
        capabilities=["Cyber-HUD component design", "Mobile responsiveness", "Micro-interaction audio"],
        status="idle",
        current_task="Standby",
        task_count=138,
        token_velocity=0,
        total_tokens=364100
    ),
    AgentManifest(
        id="agent-seo",
        name="SEO-AMPLIFIER",
        role="Metadata, Web Vitals & Search Index Optimizer",
        category="Marketing",
        autonomy_tier="Autonomous",
        allowed_tools=["lighthouse_auditor", "meta_tag_generator", "sitemap_validator"],
        risk_level=RiskLevel.LOW,
        project_scope=["portfolio"],
        execution_policy="Generates semantic meta tags and evaluates Core Web Vitals.",
        model="Gemini 2.0 Flash",
        avatar="📈",
        color="#f97316",
        capabilities=["OpenGraph optimization", "Core Web Vitals audit", "Sitemap generation"],
        status="idle",
        current_task="Standby",
        task_count=29,
        token_velocity=0,
        total_tokens=62100
    ),
    AgentManifest(
        id="agent-cost",
        name="COST-OPTIMIZER",
        role="Cloud Billing & Hard Zero-Incurrence Guardrail Sentinel",
        category="Governance",
        autonomy_tier="Autonomous",
        allowed_tools=["billing_auditor", "tier_calculator", "budget_verifier"],
        risk_level=RiskLevel.LOW,
        project_scope=["*"],
        execution_policy="Real-time billing audit. Enforces $0.00 zero-cost guardrail on personal-engineering-os-2026.",
        model="Gemini 2.5 Flash",
        avatar="💰",
        color="#84cc16",
        capabilities=["Cloud budget monitoring", "Free-tier verification", "Resource rightsizing"],
        status="monitoring",
        current_task="Enforcing $0.00 / month hard guardrail",
        task_count=210,
        token_velocity=15,
        total_tokens=412300
    ),
    AgentManifest(
        id="agent-mon",
        name="METRICS-PROBER",
        role="Host Telemetry, Ports & Socket Health Observer",
        category="Observability",
        autonomy_tier="Autonomous",
        allowed_tools=["psutil_stream", "port_scanner", "socket_probe"],
        risk_level=RiskLevel.LOW,
        project_scope=["*"],
        execution_policy="Read-only host diagnostics streaming to WebSocket subscribers.",
        model="Local Daemon Engine",
        avatar="📡",
        color="#06b6d4",
        capabilities=["Multicore CPU load", "Memory footprint", "Open socket scan"],
        status="active",
        current_task="Streaming 1000ms WebSocket telemetry",
        task_count=490,
        token_velocity=85,
        total_tokens=920400
    ),
    AgentManifest(
        id="agent-recovery",
        name="RECOVERY-GUARDIAN",
        role="Disaster Recovery, Health Restoration & Panic Protocol",
        category="Resilience",
        autonomy_tier="Guardrailed",
        allowed_tools=["state_restorer", "process_killer", "backup_manager"],
        risk_level=RiskLevel.HIGH,
        project_scope=["*"],
        execution_policy="Rollbacks and emergency state restorations. Master panic protocol execution.",
        model="Gemini 2.5 Pro",
        avatar="🚨",
        color="#ef4444",
        capabilities=["1-click panic killswitch", "Rollback orchestration", "Crash recovery"],
        status="idle",
        current_task="Standby",
        task_count=18,
        token_velocity=0,
        total_tokens=48200
    )
]

def get_agent_list() -> List[AgentManifest]:
    from core.observability import collector
    for a in SPECIALIZED_AGENTS:
        if a.id in collector.agent_runs:
            m = collector.agent_runs[a.id]
            # Add live executions to base count
            base_count = getattr(a, "_base_task_count", None)
            if base_count is None:
                a._base_task_count = a.task_count
                base_count = a.task_count
            a.task_count = base_count + m.get("execution_count", 0)
    return SPECIALIZED_AGENTS

def get_agent_by_id(agent_id: str) -> Optional[AgentManifest]:
    agents = get_agent_list()
    return next((a for a in agents if a.id == agent_id), None)

